# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41b3f8e8965e53964f560d16d8881ab8a638719c06282b4a066886fa1b513ef6b14375cf14acb99d268a46150db613ff5d5b54dbcfb6dae725d092c9c3135ec6

test:
  secret_key_base: f689695966d389287ce1e5d775b9eab879a4b582ce9ef7e5dbf482d1743d454cda537c223bed885c65328ed5246c932e054c3f7440e5b78e169a3221fc665dcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
